// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABn9Gt0G8WVnczVYREBKG7guC_49kKc5o',
    appId: '1:269000261298:android:29602ce1fc40c741f613ab',
    messagingSenderId: '269000261298',
    projectId: 'getin-coffee',
    storageBucket: 'getin-coffee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeZ2vr3APBL_zfhm4x7MkW6dN8ZyP13pU',
    appId: '1:269000261298:ios:bcfcf38757e4fcf0f613ab',
    messagingSenderId: '269000261298',
    projectId: 'getin-coffee',
    storageBucket: 'getin-coffee.firebasestorage.app',
    androidClientId: '269000261298-o99divgp0uhuldgi6uhcp9a51pbjnckg.apps.googleusercontent.com',
    iosClientId: '269000261298-dl9ubqksj3ta6g933tftl5tutghfle82.apps.googleusercontent.com',
    iosBundleId: 'com.getincoffee.getinCoffee',
  );

}